# This is a basic workflow to help you get started with Actions

name: Build Website

# Controls when the action will run. Triggers the workflow on pull request
on:
  push:
    branches: 
      - master
    paths:
      - 'docs/src'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: docs
        steps:
          - uses: actions/checkout@v2
            with:
              ref: ${{ github.head_ref }}
          - uses: actions/setup-node@v1
            with:
              node-version: "12.x"
          - name: Install
            run: npm install
            env:
                CI: true

          - name: Build
            run: npm run build
            
          - uses: stefanzweifel/git-auto-commit-action@v4
            with:
                commit_message: Build Website





